---
# PostgreSQL Secret
# ⚠️ WARNING: Change these default passwords in production!
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: keycloak
type: Opaque
stringData:
  username: postgres
  password: postgres-password-change-me
  database: postgres

---
# Keycloak Database Connection Secret
# ⚠️ WARNING: Change these default passwords in production!
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  username: keycloak
  password: keycloak-password-change-me
  database: keycloak

