---
apiVersion: v1
kind: LimitRange
metadata:
  name: rosa-101-limits
spec:
  limits:
    - type: Pod
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 16Mi
    - type: Container
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 16Mi
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      maxLimitRequestRatio:
        cpu: "10"
