apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIuaW8iOiB7CgkJCSJhdXRoIjogInh4eHh4eCIKCQl9Cgl9Cn0K
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-auth-secret
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
