apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-ddl
  namespace: db-migration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-credentials-ddl
    creationPolicy: Owner
  data:
    - secretKey: PGUSER
      remoteRef:
        key: db-migration/ddl
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: db-migration/ddl
        property: password
    - secretKey: PGHOST
      remoteRef:
        key: db-migration/ddl
        property: host
    - secretKey: PGPORT
      remoteRef:
        key: db-migration/ddl
        property: port
    - secretKey: PGDATABASE
      remoteRef:
        key: db-migration/ddl
        property: dbname
  dataFrom: []
