# Database connection env injected into stateful microservices
---
apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: retail-hub
  labels:
    app.kubernetes.io/part-of: enterprise-retail-hub
type: Opaque
stringData:
  PGHOST: postgres
  PGPORT: "5432"
  PGDATABASE: retail
  PGUSER: postgres
  PGPASSWORD: retail-demo-change-me
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-env
  namespace: retail-hub
  labels:
    app.kubernetes.io/part-of: enterprise-retail-hub
data:
  NODE_ENV: production
  CATALOG_SERVICE_URL: http://catalog-service:8081
  CART_SERVICE_URL: http://cart-service:8082
  ORDER_SERVICE_URL: http://order-service:8083
  API_GATEWAY_URL: http://api-gateway:8080
