apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpa-sbom-pvc
  namespace: trustification
  labels:
    app: tpa-service
    managed-by: kustomize
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpa-vex-pvc
  namespace: trustification
  labels:
    app: tpa-service
    managed-by: kustomize
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

